// src/i8.js
export const content = {
  EN: {
    title: "Guard Schedule Planner",
    subtitle: "Save time and headache with automated scheduling!",
    autoFillButton: "Ashot Team",
    setAvailability: "Set Availability",
    availabilityInstructions: "Select the shifts each guard is available for on each day:",
    checkAll: "Check All",
    uncheckAll: "Uncheck All",
    submit: "Submit",
    reset: "Reset",
    shiftCountTitle: "Shift Count Per Guard",
    noShift: "No shift",
    alertTitle: "Alert Messages",
    enterNames: "Enter guard names (comma-separated):",
    namePlaceholder: "Adir, Ofir, Shahar",
    week: "Week",
    guard: "Guard",
    numberOfShifts: "Number of Shifts",
    scheduleOverview: "Schedule Overview",
    shiftDay: "Shift/Day",
    guardNames: {
      Adir: "Adir",
      Ofir: "Ofir",
      Shahar: "Shahar",
      Itay: "Itay",
      Gabriel: "Gabriel",
      Ohad: "Ohad",
      Orel: "Orel",
      Ron: "Ron",
      Sam: "Sam",
      Yael: "Yael"
    },
    days: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    shiftTypes: ['Morning', 'Evening', 'Night']
  },
  HE: {
    title: "מתכנן לוח זמנים של המאבטחים",
    subtitle: "חסוך זמן וכאב ראש עם תכנון אוטומטי!",
    autoFillButton: "צוות עשות",
    setAvailability: "הגדר זמינות",
    availabilityInstructions: "בחר את המשמרות שבהן כל מאבטח זמין בכל יום:",
    checkAll: "סמן הכל",
    uncheckAll: "בטל סימון הכל",
    submit: "שלח",
    reset: "אפס",
    shiftCountTitle: "ספירת משמרות לכל מאבטח",
    noShift: "אין משמרת",
    alertTitle: "הודעות התראה",
    enterNames: "הכנס שמות מאבטחים (מופרדים בפסיק):",
    namePlaceholder: "אדיר, אופיר, שחר",
    week: "שבוע",
    guard: "מאבטח",
    numberOfShifts: "מספר משמרות",
    scheduleOverview: "סידור עבודה",
    shiftDay: "משמרת/יום",
    guardNames: {
      Adir: "אדיר",
      Ofir: "אופיר",
      Shahar: "שחר",
      Itay: "איתי",
      Gabriel: "גבריאל",
      Ohad: "אוהד",
      Orel: "אוראל",
      Ron: "רון",
      Sam: "סאם",
      Yael: "יעל"
    },
    days: ['ראשון', 'שני', 'שלישי', 'רביעי', 'חמישי', 'שישי', 'שבת'],
    shiftTypes: ['בוקר', 'צהריים', 'לילה']
  }
};
